version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo_data:/data/db

  data_transformer:
    build:
      context: .
      dockerfile: Dockerfile.transformer
    container_name: data_transformer
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=eu-west-3
    volumes:
      - ./output:/app/output
      - ./.env:/app/.env
    command: python data_transformation.py

  mongo_migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    container_name: mongo_migration
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./output:/app/output
      - ./.env:/app/.env
    depends_on:
      - data_transformer
    command: python mongo_migration.py

volumes:
  mongo_data:
