# Dockerfile.migration
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
COPY mongo_migration.py .
COPY .env .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "mongo_migration.py"]
